/**
 * SYMETRY TETRIX — Configuration
 * Fichier administrable : langues, devises, traductions.
 */

window.TetrixConfig = {

  // ─── DEVISES ──────────────────────────────────────────
  currencies: [
    { code: 'USD', symbol: '$',  flag: '🇺🇸', name: 'US Dollar'      },
    { code: 'EUR', symbol: '€',  flag: '🇪🇺', name: 'Euro'            },
    { code: 'CHF', symbol: 'Fr', flag: '🇨🇭', name: 'Franc suisse'    },
    { code: 'NGN', symbol: '₦',  flag: '🇳🇬', name: 'Naira nigérian'  },
    { code: 'AOA', symbol: 'Kz', flag: '🇦🇴', name: 'Kwanza angolais' },
    { code: 'MZN', symbol: 'MT', flag: '🇲🇿', name: 'Metical mozamb.' },
  ],

  // ─── LANGUES ──────────────────────────────────────────
  languages: [
    { code: 'fr', label: 'Français',  flag: '🇫🇷' },
    { code: 'en', label: 'English',   flag: '🇬🇧' },
    { code: 'pt', label: 'Português', flag: '🇵🇹' },
    { code: 'es', label: 'Español',   flag: '🇪🇸' },
    { code: 'sw', label: 'Kiswahili', flag: '🇰🇪' },
  ],

  // ─── TRADUCTIONS ──────────────────────────────────────
  i18n: {
    fr: {
      balance:     'Solde',
      play:        'JOUER',
      lines:       'Lignes',
      stake:       'Mise',
      gain:        'Gain',
      next:        'Next',
      bonus:       'Bonus',
      score:       'Score',
      time:        'Temps',
      sound:       'Son',
      language:    'Langue',
      currency:    'Devise',
      menu:        'Menu',
      soundOn:     'Activé',
      soundOff:    'Désactivé',
      chooseBet:   'Choisissez une mise pour commencer',
      insufficient:'Solde insuffisant',
      bust:        'Bust ! Aucune ligne.',
      continue:    'Continuer',
      lines_one:   'ligne',
      lines_many:  'lignes',
    },
    en: {
      balance:     'Balance',
      play:        'PLAY',
      lines:       'Lines',
      stake:       'Stake',
      gain:        'Win',
      next:        'Next',
      bonus:       'Bonus',
      score:       'Score',
      time:        'Time',
      sound:       'Sound',
      language:    'Language',
      currency:    'Currency',
      menu:        'Menu',
      soundOn:     'On',
      soundOff:    'Off',
      chooseBet:   'Choose a bet to start',
      insufficient:'Insufficient balance',
      bust:        'Bust! No lines cleared.',
      continue:    'Continue',
      lines_one:   'line',
      lines_many:  'lines',
    },
    pt: {
      balance:     'Saldo',
      play:        'JOGAR',
      lines:       'Linhas',
      stake:       'Aposta',
      gain:        'Ganho',
      next:        'Próx.',
      bonus:       'Bônus',
      score:       'Pontos',
      time:        'Tempo',
      sound:       'Som',
      language:    'Idioma',
      currency:    'Moeda',
      menu:        'Menu',
      soundOn:     'Ativado',
      soundOff:    'Desativado',
      chooseBet:   'Escolha uma aposta para começar',
      insufficient:'Saldo insuficiente',
      bust:        'Bust! Nenhuma linha.',
      continue:    'Continuar',
      lines_one:   'linha',
      lines_many:  'linhas',
    },
    es: {
      balance:     'Saldo',
      play:        'JUGAR',
      lines:       'Líneas',
      stake:       'Apuesta',
      gain:        'Ganancia',
      next:        'Sig.',
      bonus:       'Bonus',
      score:       'Puntos',
      time:        'Tiempo',
      sound:       'Sonido',
      language:    'Idioma',
      currency:    'Divisa',
      menu:        'Menú',
      soundOn:     'Activado',
      soundOff:    'Desactivado',
      chooseBet:   'Elige una apuesta para empezar',
      insufficient:'Saldo insuficiente',
      bust:        '¡Bust! Sin líneas.',
      continue:    'Continuar',
      lines_one:   'línea',
      lines_many:  'líneas',
    },
    sw: {
      balance:     'Salio',
      play:        'CHEZA',
      lines:       'Mistari',
      stake:       'Dau',
      gain:        'Faida',
      next:        'Ijayo',
      bonus:       'Bonasi',
      score:       'Alama',
      time:        'Muda',
      sound:       'Sauti',
      language:    'Lugha',
      currency:    'Sarafu',
      menu:        'Menyu',
      soundOn:     'Imewashwa',
      soundOff:    'Imezimwa',
      chooseBet:   'Chagua dau kuanza',
      insufficient:'Salio haitoshi',
      bust:        'Bust! Hakuna mistari.',
      continue:    'Endelea',
      lines_one:   'mstari',
      lines_many:  'mistari',
    },
  },
};
